### PR TITLE
moved post sidebar positioning to post.css, fixed tags positining in …

### LINKED ISSUE #15: Template: blog post
current thinking is that this template should be auto-assigned to any page that has an author, but not 100% sure that is the right approach.

### PR DESCRIPTION
**Pull request by 3vil3mpir3**
…sidebar, added padding back into main blog content area, fixed minor inconsistancies with css :not references, added method to build social share links to icons, added uri encoding where appropriate, fixed page topic/subtopic not rendering link correctly

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #15 

If your change will impact authors (new block or block variant, etc.) please update the [authoring guide](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BE481F963-643C-4066-B9D2-597596DDAD53%7D&file=authoring%20guide.docx&action=default&mobileredirect=true) and [block inventory](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BA5A312F2-2572-46C2-B174-E761DAC9BC0E%7D&file=block%20inventory.docx&action=default&mobileredirect=true) pages.

Test URLs:
- Before: https://main--blogs-keysight--hlxsites.hlx.page/tech/bench/2022/10/30/reduced-development-time-with-pathwave-test-executive-for-manufacturing
- After: https://issue15-3--blogs-keysight--hlxsites.hlx.page/tech/bench/2022/10/30/reduced-development-time-with-pathwave-test-executive-for-manufacturing

### CODE REVIEW

File: blocks/post-sidebar/post-sidebar.js [hunk 1]
```diff
@@ -56,7 +81,7 @@ export default async function decorate(block) {
 
   const picMedia = [{ media: '(min-width: 160px)', width: '160' }];
   const pic = createOptimizedPicture(authorImage, '', false, picMedia);
-  block.innerHTML = `<a class="author-image" href="${authorUrl}">${pic.outerHTML}</a>
+  block.innerHTML = `<a class="author-image" href="${encodeURIComponent(authorUrl)}">${pic.outerHTML}</a>
```
Comment (shsteimer) [inline blocks/post-sidebar/post-sidebar.js:84]: don't think you need `encodeURIComponent` here. I don't think it will cause any problems, but since it's a full path and not just a param, probably not required.

Comment (3vil3mpir3) [reply blocks/post-sidebar/post-sidebar.js:84]: fair.  Removing along with some minor css changes.
